### ISSUE TITLE
Default appearance of matInput should be 'fill', not 'outline'

### ISSUE THREAD

**Issue by st-clair-clarke** [PawelGajo/ngx-material-form-utils#1]
Hi Pawel, congrats on your excellent material form-field validator,

Is there any reason why you change the default appearance to 'outline' instead of 'fill' - the material default? This would be in keeping with the theme of material-form.

I am planning to use it in a project, so I hope some long-term maintenance is planned (.

**Comment by PabloCSScobar** [comment]
Hi, 
You are right, It would be good to change it to 'fill' - I usually use outline in my projects, that's why I set it to default :)
Until then, you can set appearance='fill' on component:
`<mfu-input appearance="fill" controlName="someField"/>`

**Comment by st-clair-clarke** [comment]
Cheers
